# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [1]:
import numpy as np
import time

In [2]:
a = [1.2, 5.4, 6, 1.59]
b = [5.2, 1.2, 1.5, 2]

# Radice quadrata
c = np.array(a)
print(np.sqrt(c))

# Potenza
c = np.array(a)
print(np.exp(c / 2))

# Vettore somma
c = np.array(a)
d = np.array(b)
print(c + d)

# Prodotto
c = np.array(a)
d = np.array(b)
print(c * d)

# Vettore equispaziato
print(np.arange(0, 30, 0.5))

# Vettore di 100 valori
print(np.linspace(1, 2, 100))

# Array 2x6
c = np.linspace(10, 20, 6)
d = np.linspace(20, 10, 6)
arr = np.append(c, d)
print(arr.reshape(2, 6))

# Prodotto scalare tra vettori
c = np.array(a)
d = np.array(b)
e = np.dot(c, d)
print("e = ", e)

# Matrice A
c = np.array(a)
d = np.array(b)
arr = np.append(c, d)
A = arr.reshape(2, 4)
print(A)

# y = A * b
d = np.array(b)
y = A * d
print(y)

# Vettore diagonale D
c = np.array(a)
D = np.diag(c)
print(D)

[1.09544512 2.32379001 2.44948974 1.26095202]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1.4949

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

In [3]:
a = [2, 2, 2, 3]
A = np.full((3, 4), a)
print(A)

a = np.identity(3, dtype="int64") * 2
b = np.array([1, 2, 3])
e = np.vstack((b, b, b))
c = np.array([10, 10, 10])
c = c.reshape((3, 1))
d = np.zeros((3, 3), dtype="int64")
B = np.hstack((a, e, d, d, c))
print(B)

identity = np.identity(5, dtype="int64") * 2
shiftUp = np.eye(5, k=1, dtype="int64")
shiftDown = np.eye(5, k=-1, dtype="int64")
C = identity - shiftDown - shiftUp
print(C)

a = np.array([2, 2, 3, 3])
b = np.array([0, 0, 5, 5])
c = np.array([0, 0, 0, 0])
D = np.vstack((a, a, c, b, b))
print(D)

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 2  0  0  1  2  3  0  0  0  0  0  0 10]
 [ 0  2  0  1  2  3  0  0  0  0  0  0 10]
 [ 0  0  2  1  2  3  0  0  0  0  0  0 10]]
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
[[2 2 3 3]
 [2 2 3 3]
 [0 0 0 0]
 [0 0 5 5]
 [0 0 5 5]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [4]:
def sumNNumbers(numbers, value):
    result = 0

    # For loop
    if value:
        for num in range(1, numbers + 1):
            if not (num % 2) == 0:
                result = result + num
        print(result)
    # numpy sum()
    else:
        num = np.arange(1, 100, 2)
        result = np.sum(num)
        print(result)

# Calling functions
sumNNumbers(100, True)
sumNNumbers(100, False)

2500
2500


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

In [5]:
# Fibonacci ricorsivo
def recurFibo(num):
    if num <= 2:
        return 1
    else:
        return recurFibo(num - 1) + recurFibo(num - 2)

# Fibonacci iterativo
def fib(num):
    actual, result = 0, 1

    for i in range(num - 1):
        actual, result = result, actual + result

    return result

# Formula di Binet
def fiboBinet(num):
    return int(((((1 + np.sqrt(5))/2)**num) - (((1 - np.sqrt(5))/2)**num)) / np.sqrt(5))

# Fibonacci iterativo con numpy
def fibN(num):
    if num <= 2:
        return 1

    fibo = np.ones(num, dtype=int)

    for i in range(2, num):
        fibo[i] = fibo[i - 1] + fibo[i - 2]

    return fibo[-1]

start = time.time()
a = recurFibo(24)
end = time.time() - start
print(a)
print(end)

start = time.time()
a = fib(24)
end = time.time() - start
print(a)
print(end)

start = time.time()
a = fiboBinet(24)
end = time.time() - start
print(a)
print(end)

start = time.time()
a = fibN(24)
end = time.time() - start
print(a)
print(end)

46368
0.014003276824951172
46368
0.0
46368
0.0
46368
0.0
