##                                                               Esercitazione 7 - 4 Aprile 2023

## Nota 1.
La funzione *scipy.linalg.lu(A)*  , presa in input una matrice A a rango massimo, restituisce in output le matrici $P^T$,L,U,  della fattorizzazione di LU della matrice A in maniera tale che PA=LU (restituisce la matrice di permutazione trasposta)

In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import lu
A = np.array([[2, 1], [3, 4]])
# Restituisce in output la trasposta della matrice di Permutazione
PT, L, U = lu(A)
P = PT.T.copy()  # P è la matrice di permutazione
print("A=", A)
print("L=", L)
print("U=", U)
print("P=", P)
# LU è la fattorizzazione di P*A (terorema 2)
A1 = P@A  # equivale al prodotto matrice x matrice np.dot(P,A)
A1Fatt = L@U  # equivale a np.dot(L,U)
print("Matrice P*A \n", A1)
print("Matrice ottenuta moltipicando Le ed U \n", A1Fatt)


A= [[2 1]
 [3 4]]
L= [[1.         0.        ]
 [0.66666667 1.        ]]
U= [[ 3.          4.        ]
 [ 0.         -1.66666667]]
P= [[0. 1.]
 [1. 0.]]
Matrice P*A 
 [[3. 4.]
 [2. 1.]]
Matrice ottenuta moltipicando Le ed U 
 [[3. 4.]
 [2. 1.]]


## Nota 2
La funzione *scipy.linalg.cholesky(a, lower=True)*, presa in input una matrice simmetrica e definta positiva restituisce in output la matrice L triangolare inferiore tale che $A=L \cdot L^T$. Se la matrice simmetrica in input non è  definita positiva, restituisce un errore.

In [2]:
from scipy.linalg import cholesky
A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
print(A)


[[ 2  1  3]
 [ 1  5  7]
 [ 3  7 12]]


In [3]:
L = cholesky(A, lower=True)
print(L)
A1 = L@L.T
print("A1=\n", A1)


[[1.41421356 0.         0.        ]
 [0.70710678 2.12132034 0.        ]
 [2.12132034 2.59272486 0.8819171 ]]
A1=
 [[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Nota 3
La funzione *scipy.linalg.qr(a)*, presa in input una matrice A (nxn)  a rango massimo, restituisce in output le matrici Q (ortogonale di dimensione nxn) ed una matrice R (nxn) triangolare superiore tale che $A=Q \cdot R$

In [4]:
from scipy.linalg import qr
A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
Q, R = qr(A)
print("Q= \n", Q)
print("R= \n", R)
A1 = Q@R
print(A1)


Q= 
 [[-0.53452248  0.6882472  -0.49051147]
 [-0.26726124 -0.6882472  -0.67445327]
 [-0.80178373 -0.22941573  0.55182541]]
R= 
 [[ -3.74165739  -7.48331477 -13.09580085]
 [  0.          -4.35889894  -5.50597761]
 [  0.           0.           0.42919754]]
[[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Esercizio 1. 
Facendo uso dei numpy array, implementare una funzione Lsolve(L,b), che, presa  in input una matrice L, triangolare inferiore,  e il vettore termine noto b, risolva il sistema lineare Lx=b, con il metodo della sostituzione in avanti e restituisca in output: la soluzione del sistema lineare ed un flag: flag=  0, se sono soddisfatti i criteri di applicabilità flag= 1, se non sono soddisfatti. (NB. Come test di applicabilità controllare che la matrice L sia quadrata e che non si annulli nessun elemento della diagonale).

In [5]:
def Lsolve(L, b):
    # test dimensione sulla possibile differenza tra righe e colonne
    m, n = L.shape
    flag = 0
    if n != m:
        print("Matrice non quadrata")
        flag = 1
        x = []
        return x, flag

    # Test sulla singolarità: prodotto delle diagonali per vedere che queste non si annullino
    if np.all(np.diag(L)) != True:
        print("Diagonale nulla, matrice triangolare inferiore")
        flag = 1
        x = []
        return x, flag

    # Algoritmo vero e proprio
    x = np.zeros((n, 1))

    # Eseguo il prodotto scalare tra la riga i-esima e le i-1 componenti della soluzione appena calcolata
    for i in range(n):
        s = np.dot(L[i, :i], x[0:i])
        x[i] = (b[i] - s) / L[i, i]

    return x, flag


L = np.array([[2, 0, 0], [6, 4.0, 0], [7.0, 2.0, 4.0]])
print(L)
b = np.sum(L, axis=1).reshape(3, 1)
print(b)

x, flag = Lsolve(L, b)
print("Soluzione", x)


[[2. 0. 0.]
 [6. 4. 0.]
 [7. 2. 4.]]
[[ 2.]
 [10.]
 [13.]]
Soluzione [[1.]
 [1.]
 [1.]]


## Esercizio 2. 
Facendo uso dei numpy array, implementare una funzione Usolve(L,b), che, presa  in input una matrice U, triangolare superiore,  e il vettore termine noto b, risolva il sistema lineare Ux=b, con il metodo della sostituzione all'indietro e restituisca in output: la soluzione del sistema lineare ed un flag: flag=  0, se sono soddisfatti i criteri di applicabilità flag= 1, se non sono soddisfatti. (NB. Come criteri di applicabilità controllare che la matrice L sia quadrata e che non si annulli nessun elemento della diagonale).

In [6]:
def Usolve(U, b):
    # test dimensione sulla possibile differenza tra righe e colonne
    m, n = U.shape
    flag = 0
    if n != m:
        print("Matrice non quadrata")
        flag = 1
        x = []
        return x, flag

    # Test sulla singolarità: prodotto delle diagonali per vedere che queste non si annullino
    if np.all(np.diag(U)) != True:
        print("Diagonale nulla, matrice triangolare superiore")
        flag = 1
        x = []
        return x, flag

    x = np.zeros((n, 1))

    # Il passo dell'algoritmo agisce al contrario perchè la matrice che viene analizzata è diversa
    for i in range(n-1, -1, -1):
        s = np.dot(U[i, i + 1:n], x[i + 1:n])
        x[i] = (b[i] - s) / U[i, i]

    return x, flag


U = L.T
print(U)
b = np.sum(U, axis=1).reshape(3, 1)
print(b)

x, flag = Usolve(U, b)
print("Soluzione", x)


[[2. 6. 7.]
 [0. 4. 2.]
 [0. 0. 4.]]
[[15.]
 [ 6.]
 [ 4.]]
Soluzione [[1.]
 [1.]
 [1.]]


## Esercizio 3
- si implementi una function LUsolve(P,L,U,b) che risolve il sistema lineare Ax=b nel caso di fattorizzazione $PA = LU$ assegnata,
combinando i metodi di risoluzione in avanti ed all'indietro  precedentemente implementati.
- si testi sulla matrice A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]]) con termine noto b scelto in maniera tale che la soluzione esatta del sistema lineare sia il vettore formato da tutti 1.

In [7]:
def LUSolve(P, L, U, b):
    # PA = LU
    # Ax = b -> PAx = Pb -> L(Ux) = Pb
    y, flag = Lsolve(L, np.dot(P, b))
    x, flag = Usolve(U, y)
    return x, flag


A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.sum(A, axis=1)

P, L, U = lu(A)
sol, flag = LUSolve(P.T, L, U, b)
print(sol)


[[1.]
 [1.]
 [1.]
 [1.]]
